language: node_js
dist: trusty
node_js:
- '10'
- '8'
- '6'
matrix:
  fast_finish: true
  allow_failures:
    - node: 6
    - node: 10
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAIEKKCTFCDTGKKHMA
  - secure: lsChDqoBUH9FaP1UbRz4yL9B3IxFTXg75WPiFGmaKmARGJ4cb6YvGFnJkSrrT6IN7aovlkR4rLCbEqyRsFmEUuAdoNa/zBIwVhc03QYgaX6cqdSubN5QvfCqKJyDiPJ+DqZyuPmUTfr8Eirh1/BWwufMkdlqFRTNBH2PF5FK1gzA9SIc+bC0s3ySuWtxYb//ovx23A+Tow7+hftzrrQm23Mdze/xoqnlS6uhjWTzhwdvsk2r+I/47M/3lTHcIDGLrgDJ9tbwb3ZfLfnk2arHGBLYSKWvNwq+ACy4CMSfIjLZCZJ93YOJbMomt0usjQZG8C8PzfpjHqrEcuN6jOpv3Vou+w9oILoyGnWC06yi7VFiUa0vPkd0fEEHcl9cL1SdLg8hgni9zVND5+We/vDLpGJAlp+n0PtPK6CvMk8r3OI79DWCDO+SjMs0goC1u6iArLz2kPdiIPmIi60MG3tHmcip9bajNzfy8dXGvedGVOSNLQv9uYhOXmu4Eb9eI6SDMnXLZADSp6TezHLOxr1IDenWA5VTEOx5UrDH0gLMQN1bXYD24N5jKoFRTf5Ucx+m2Luu7R60mn5LzcqtAUNLm3NJyx3sBGwlSEl3K75GgIow9yfi1MWiOWD1xLlemvpi8HN+som4DlYJObZJzMAH37TkI8hdFHfhcQbEcGgpK5M=
  - secure: X64AGFc6rKkfcg+1/iUHM9IbEfGCjEWyNeHQBuh3WuRlkc5C+x5PLQQ4RpSZqqf7APH+/xmjYHP6Xt/T5O2wM2rimH4yWfm45xY+HKamWbelCSQjWG6VeKAwVJMKiqInAjzYUaf2qGZoHtGeQ2fzJrCOkqofVTXLfq9AyA7BU9LMd0Sp9bt2KJSGaguc+Ajm4kX8NQ3Uop1of+EQiGmTJKWeoFdjuuY8YQgjnkk7Mh5mzbNTdxeQAj9URsZSiU614q5zpkgobPHdTdU/hsOmY/ELwwsSIpA5Zic/a69HHjRZvKnfXp48BXBsPiv6F6cTtjtpyyAvYq61uwEDF5N+E/3lP/qSbShJGwfVBupkfceh0Tc/amtBObBPTRlpMiQrs8PSgVRvlCWLpuUeJqoAmHi9Eayu9RW7a5/ULBpPa0a3WYKciFzcf1KzPusDQgzwzeyLTm67D/pwxwY8gghTWFwrqhcLnprnpRIlvjWSo9S4tYqKhxD6tZdpHa8hxJcpTxiY8k/QHqGvwPWKpW4QNUQigE7L8c77oSo718Wd9cDRifqMr/tjrzCRRHOq75lRyu1rr0ounDPQwKGoYh3dbgSrNiD9rW4B9qTKOnb5B+kGtbeCfwYLrok17oGt0UF/wBgKVib1uLC2FZXJijjpIDNPIbuOl88a9iXPKP9SZ9o=
  - secure: CIl8S5L9EilujMCRbAhYhlEh4igwiQWnApKO9m/1rCy4TOCYzj6rjCH8smB1ScvD0Ikw5hmth35XS9xRUqNrlu8LXz+pW0STQW9POjHYIV8ADSHYUQq5NgeXcphHKvJIprpjDVrRrTS1irMOONu5SQoFfMkEiBsrb6P5J49oaLnK7t4BwhRjTpweVAyY0tpFG2upQGxlQdsztxaOYCa8fvdJuWIfp7LkZU79qzZkLwvev8PRh/K+GKsYrOtgKW1bL3oqVYTyUFyzpExYOUzOVfy9zKAmEbHVVDx4quiSiTUZEIhIQJ4Ky1svAWM8pDZz9pYKh1XS50pgA1fsYwSnJvu/y9F0fol+Ku6yvmHXba6mr3s3qZ0YqPikBCCYUHfbA/ASR0+zMUV0THsXbSgMmeMPRBZoI0HqulaqYoCsXRFBdvJNGQfAQ+Rs493KK2MbVEPQbiRGkPMSfAOtYCXBwazEmqJXF6vkYsLb/jq9WnIoG8cwWDD7vTTyb3QiSmS0YAMW+1rxAW/PRztnAIMeKEBsu7pkY8GkZfQ+eG98nG4OeaDo4iOGC/FGh7uASWTEXaC0o/FSzaQoZMX5/TiE3xzni15l5bPg2OXcjdf04JkZHLbok2pDes+4rRYad4FvJd6H9Ud9TfqmooLsw1IKsLuV3Q75ozhH5BsE4rsZpOA=
  - SENTRY_ORG=randytarampi
  - SENTRY_PROJECT=posts
  - SENTRY_PROJECT=posts
  - SENTRY_LOG_LEVEL=debug
before_install:
- uname -a
- lscpu
- npm install -g npm
- export NODE_ENV=prd;
- git config --global url."https://github.com/".insteadOf ssh://git@github.com/
- git config --global url."https://".insteadOf ssh://
script: npm run travis
before_deploy:
- mkdir -p ../dpl_cd_upload
- tar -zcf ../dpl_cd_upload/me.posts.tar.gz -C ./ .
- git config --local user.name "Travis"
- export TRAVIS_AUTHOR=travis@randytarampi.ca
- export COMMIT_AUTHOR=`git --no-pager show -s --format='%ae' \`git rev-parse\``
- git config --local user.email $TRAVIS_AUTHOR
- shopt -s extglob
- if [[ "$TRAVIS_COMMIT_MESSAGE" =~ !(^0.0.0-[0-9]{10}$) ]]; then
  npm version "0.0.0-`date -u +%s`";
  fi;
deploy:
- provider: script
  script: NODE_ENV=prd npm run deploy
  skip_cleanup: true
  on:
    branch: master
    node: 8
- provider: releases
  api_key:
    secure: WYoyquzsGn8vtgnLHC7tvCvysH+yi1JPhlATlchP4WwRJiori9klsUV7tBCStB/CbLe6wP4kINcyrKpv6SS9+QgYQDvNx7dZP9nTjtpTAG5o18sIZLTkzFUUv5E2usCiF38xLE33VbxhFa3VfhmLQUypntFM6AZS/mt+GQq28aKaoQLeV1aSJRpoyGCvamPrFB/LahTNVFe/U/ZCtfae6trqV4CeM5bTkeCt4llsR4lBTvkPOS+jpMr18VXVrgMwlWvOVL8mneowS7FNH6Wp2AAr5GT/LkspFrZ/Rcx7EhYgiah+A3whFGckED24uRjuxSsa3IVz8BtL7vTAbFBQrrSUI3scM0rXhA91ILtE7ZVLzhxtve22UUi+5/tkwcR06PmOa8bKtLcj2qRg5QSQxSoaJ7bQshcC9udYEjIs0SUfwsCqb8M61S+jbOFQGV+5MZif5dLrv5kh2UBatIiSC0v1MxIWPWObHkJ1Dh0zIunyvwtXEHwz6LSuEW1HNB4Ow5MH9vbpAK+oZmROdgyvhsXs8AvTxCwZH+jzEsfmL0VtBkfIu6xgdxRp7KXVcQY9Ca5xgyVjozmuiIX2NaHLnGYVkStWHesPJEH6TbA57702ijEe6rZljExpshvEB+VJ0NDzcwJ1ktMPIS1wwIUxet0zgYFR8+/hzYL5+pUp6rE=
  file: me.posts.tar.gz
  skip_cleanup: true
  on:
    branch: master
    node: 8
after_deploy:
#- npm version preminor -m "[Travis] Prepare version %s";
- git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG} HEAD:master;
notifications:
  slack:
    secure: g0wMZBg1xSjZZGIneSZMyvpPMX+js/Fi0Ny2onu8qfb5Fy1pPiKiwvOKjHFVg6F3D4/ZBxGfHieQ3SMyQCFegebEYL/lcUw766B90C1Vk2/5vTqL8CJsnPM7n+rZgERW5vWAQ3/zbcW3Qt8F0u/A7vu5YpY5jgKXlTqfsE4Aq85d0yqcFkO8IqWL7i3EsIXrS06M8N5vN2zZpSqyQV6Jm0Ph5lw3udG+Z745q6n9Ki9TPAxNcLwlr3hNKyngm9yXE5RjEGdNPYNuEy90vSGxzujbRNa7nY0Nr5m81cqnX9XT1NlizMj6tkvbNP4T6X8BG8dasiGMSYK3h4tyZW09Gp/ECDpTgHYIOocsReZ8kcbTDvUvCz7sslqRnDFoO8YmJnK+FwtG3nkGC3a4kNDkgJnoLYvmyB60Z/wszaxhZ6ygWutEnA8ZLy3axm7NRFdqURLiBheCTCWh4pqZ+FV2EpT+o1kAeFLu02S/OVHNY2VV5/DPvtYN4Mt+v9EaJJ6bmKmB2VpebpdTDv8vcYySJ364e9doRhXKbVp1Elnl9nduuwW8D1wp+Yh5rCgaYD6Ta6E73QPcZ3y/cP6pLTJ+k0ZeU9nmGGPS8j4plXBsBLjfuF3bbp9VmZzdqapVOsEgK/RmSWKfvtJaCrAaJcA/RG4OXQ4F4O35QDxoYGf0Io0=
